In [1]:
''' FINAL'''
''' Taboada Rodas Oscar '''
'''Regresion lineal multiple'''

' Taboada Rodas Oscar '

# FINAL INTELIGENCIA ARTIFICIAL SIS420
TABOADA RODAS OSCAR


In [1]:
import os
import numpy as np
from matplotlib import pyplot
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [38]:
data = pd.read_csv('DATASET VEHICULOS RAW.csv')
data.head()

Marca  Modelo (Ej: 2021, 2016)  Número de puertas  Número de asientos  \
0     12                     2017                  5                   5   
1     12                     2013                  4                   5   
2     19                     2019                  5                  12   
3     30                     2020                  2                   3   
4     10                     2001                  5                   5   

   Condición del vehículo  Tipo  Transmisión  Tipo de Combustible  \
0                       3     2            1                    1   
1                       2     2            1                    1   
2                       2     4            1                    1   
3                       2     1            1                    3   
4                       3     2            1                    1   

   Kilometraje (recorrido en Km)  Color  Procedencia  Cilindrada (en cc)  \
0                        42397.0      4            4                1200   
1                           60.0     14            3                3500   
2                            0.0      7            3                3700   
3                          850.0     14            4                 800   
4                        24900.0     10            4                3000   

   Estado de la pintura  ¿La pintura está en buen estado?  \
0                     1                                 1   
1                     1                                 1   
2                     1                                 1   
3                     1                                 1   
4                     1                                 1   

   ¿El vehículo tuvo algún accidente?   \
0                                    2   
1                                    2   
2                                    2   
3                                    2   
4                                    2   

   ¿El vehículo cuenta con todos los accesorios?   Costo en $us  
0                                               2       27000.0  
1                                               2       21500.0  
2                                               2       37800.0  
3                                               2        3900.0  
4                                               2       10500.0

In [39]:
# data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 935 entries, 0 to 934
Data columns (total 17 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marca                                           935 non-null    int64  
 1   Modelo (Ej: 2021, 2016)                         935 non-null    int64  
 2   Número de puertas                               935 non-null    int64  
 3   Número de asientos                              935 non-null    int64  
 4   Condición del vehículo                          935 non-null    int64  
 5   Tipo                                            935 non-null    int64  
 6   Transmisión                                     935 non-null    int64  
 7   Tipo de Combustible                             935 non-null    int64  
 8   Kilometraje (recorrido en Km)                   935 non-null    float64
 9   Color                                      

In [40]:
X = data[['Marca', 'Modelo (Ej: 2021, 2016)', 'Número de puertas', 'Cilindrada (en cc)', 'Tipo', 'Condición del vehículo', 'Kilometraje (recorrido en Km)', 'Transmisión']].to_numpy()
X


array([[1.2000e+01, 2.0170e+03, 5.0000e+00, ..., 3.0000e+00, 4.2397e+04,
        1.0000e+00],
       [1.2000e+01, 2.0130e+03, 4.0000e+00, ..., 2.0000e+00, 6.0000e+01,
        1.0000e+00],
       [1.9000e+01, 2.0190e+03, 5.0000e+00, ..., 2.0000e+00, 0.0000e+00,
        1.0000e+00],
       ...,
       [1.7000e+01, 1.9920e+03, 5.0000e+00, ..., 3.0000e+00, 3.0000e+02,
        2.0000e+00],
       [1.3000e+01, 2.0120e+03, 5.0000e+00, ..., 2.0000e+00, 9.0000e+04,
        1.0000e+00],
       [4.0000e+00, 2.0200e+03, 4.0000e+00, ..., 2.0000e+00, 5.0000e+03,
        2.0000e+00]])

In [41]:
y = data['Costo en $us'].to_numpy()
y

array([2.7000e+04, 2.1500e+04, 3.7800e+04, 3.9000e+03, 1.0500e+04,
       2.3000e+04, 1.7900e+04, 3.6800e+04, 2.7000e+04, 1.8800e+04,
       9.8000e+03, 2.7000e+04, 1.3900e+04, 1.2000e+04, 1.4000e+04,
       6.7000e+03, 5.7500e+04, 1.0500e+04, 2.1500e+04, 6.5000e+04,
       7.6000e+03, 7.8000e+03, 8.0000e+04, 1.4500e+04, 2.6700e+04,
       9.8000e+03, 1.1800e+04, 1.4500e+04, 1.0500e+04, 1.0500e+04,
       1.3200e+04, 1.0000e+04, 8.0000e+03, 1.5000e+04, 2.3000e+04,
       2.4000e+04, 2.5000e+03, 7.4000e+04, 1.6400e+04, 3.4000e+03,
       1.2500e+04, 1.4000e+04, 2.1500e+04, 4.2500e+04, 6.0000e+03,
       8.8000e+03, 1.1500e+04, 2.2900e+04, 1.8000e+04, 1.0300e+04,
       1.6200e+04, 1.5000e+04, 2.6500e+04, 1.3000e+04, 7.2000e+03,
       1.0500e+04, 1.6000e+04, 2.8000e+04, 2.6000e+04, 1.7500e+04,
       4.3000e+04, 2.1000e+04, 2.1900e+04, 1.7500e+04, 2.4900e+04,
       1.3500e+04, 2.3900e+04, 2.4800e+04, 2.1900e+04, 3.2800e+04,
       1.8500e+04, 2.1000e+04, 3.4000e+04, 2.8900e+04, 3.9500e

In [42]:
def  normalizarCaracteristicas(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma
    
    return X_norm, mu, sigma

In [43]:
X_norm, mu, sigma = normalizarCaracteristicas(X)

print(X)
print('Media calculada:', mu)
print('Desviación estandar calculada:', sigma)
print(X_norm)

[[1.2000e+01 2.0170e+03 5.0000e+00 ... 3.0000e+00 4.2397e+04 1.0000e+00]
 [1.2000e+01 2.0130e+03 4.0000e+00 ... 2.0000e+00 6.0000e+01 1.0000e+00]
 [1.9000e+01 2.0190e+03 5.0000e+00 ... 2.0000e+00 0.0000e+00 1.0000e+00]
 ...
 [1.7000e+01 1.9920e+03 5.0000e+00 ... 3.0000e+00 3.0000e+02 2.0000e+00]
 [1.3000e+01 2.0120e+03 5.0000e+00 ... 2.0000e+00 9.0000e+04 1.0000e+00]
 [4.0000e+00 2.0200e+03 4.0000e+00 ... 2.0000e+00 5.0000e+03 2.0000e+00]]
Media calculada: [1.58310160e+01 2.01181711e+03 4.30588235e+00 2.45687380e+03
 1.66951872e+00 2.47486631e+00 7.52282727e+04 1.40855615e+00]
Desviación estandar calculada: [1.09586144e+01 8.14755146e+00 8.87535582e-01 2.11312218e+03
 7.77271578e-01 7.14374457e-01 4.52061183e+05 4.91566905e-01]
[[-0.34958945  0.63612826  0.78207304 ...  0.73509584 -0.07262573
  -0.8311303 ]
 [-0.34958945  0.14518321 -0.34464235 ... -0.66473025 -0.16627898
  -0.8311303 ]
 [ 0.28917743  0.88160078  0.78207304 ... -0.66473025 -0.16641171
  -0.8311303 ]
 ...
 [ 0.10667261 

In [46]:
m, n = X.shape
X_ready = np.concatenate([np.ones((m, 1)), X_norm], axis=1)

In [47]:
def calcularCosto(X, y, theta):
    m = y.size
    J = 0
    h = np.dot(X, theta)
    # print(h)
    J = (1/(2 * m)) * np.sum(np.square(h - y))
    return J

In [48]:
# theta=np.array([0.1, 1.0, 0.1, 0.1, 1.0, 0.1])
# theta = np.random.rand(6)
theta = np.zeros(9)
JJ = calcularCosto(X_ready, y, theta)
print(f"con theta:{ theta } se obtiene un costo de: {JJ}")

con theta:[0. 0. 0. 0. 0. 0. 0. 0. 0.] se obtiene un costo de: 320599721.12352943


In [49]:
def calcularDescensoGradiente(X, y, theta, alpha, numero_iteraciones):
      m = y.shape[0]
      theta = theta.copy()
      J_historico = []

      for i in range(numero_iteraciones):
        theta = theta - (alpha / m) * (np.dot(X, theta) - y).dot(X)
        J_historico.append(calcularCosto(X, y, theta))
        return theta, J_historico

In [50]:
theta = np.zeros(9)

num_ite = 100000
alpha = 0.001

theta, J_historico = calcularDescensoGradiente(X_ready, y, theta, alpha, num_ite)
print(f"los valores de theta calculados son: { theta }")
print(f"con un costo de: { J_historico[-1]} ")


los valores de theta calculados son: [21.50303422 -3.03287723  4.36660171  1.51624225  1.6397769   3.12868378
 -3.82341789 -0.94716375 -2.80799999]
con un costo de: 320071177.06232464 


In [51]:
y_pred = np.dot([1, 2, 2018, 4, 3500, 3, 2, 18000, 1], theta)
print(y_pred)

-2477.4925800131377


In [52]:
def CalcularthetaEcuacionNormal(X, y):
    theta = np.zeros(X.shape[1])
    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)
    return theta

In [53]:
X_ren = np.concatenate([np.ones((m, 1)), X], axis=1)

In [54]:
theta = CalcularthetaEcuacionNormal(X_ren, y);
print(f"los valores de theta calculados son: { theta }")

los valores de theta calculados son: [-7.11552250e+05 -2.07359086e+02  3.68185651e+02  8.57852232e+02
  4.54988164e-01  3.23458322e+03 -3.78817161e+03 -1.16167013e-03
 -3.64447834e+03]


In [55]:
#'Marca', 'Modelo (Ej: 2021, 2016)', 'Número de puertas', 'Cilindrada (en cc)', 'Tipo', 'Condición del vehículo', 'Kilometraje (recorrido en Km)', 'Transmisión'
#527
X_array = [1, 2, 2018, 4, 3500, 3, 2, 18000, 1]
price = np.dot(X_array, theta)

print('Precio de un automovil (usando la ecuación de la normal): ${:.0f}'.format(price))

Precio de un automovil (usando la ecuación de la normal): $34518
