# FINAL INTELIGENCIA ARTIFICIAL SIS420
TABOADA RODAS OSCAR


# RED NEURONAL PARA COTIZACION DE AUTOS

Este ejemplo considera los siguientes objetivos:
- Cargar datos desde un archivo CSV para usar con Keras.
- Definir y compilar un modelo de Perceptron multicapa en Keras.
- Evaluar un modelo Keras en un conjunto de datos de validación.

Los pasos para poder crear este modelo, son los siguientes:
1. Cargar datos.
2. Definir el Modelo.
3. Compilar el Modelo.
4. Entrenar el Modelo.
5. Evaluar el Modelo.
6. Unir todos los pasos anteriores.

## Cargar datos
### Dataset
Atributos del dataset:
1. Marca
2. Modelo (Ej: 2021, 2016)
3. Número de puertas
4. Número de asientos
5. Condición del vehículo
6. Tipo
8. Transmisión
9. Tipo de Combustible
7. Kilometraje (recorrido en Km)
10. Color
11. Procedencia
12. Cilindrada (en cc)
13. Estado de la pintura
14. ¿La pintura está en buen estado?
15. ¿El vehículo tuvo algún accidente?
16. ¿El vehículo cuenta con todos los accesorios?
17. Costo en $us
18. Variable 0 o 1

### Cargar dataset
En el siguiente código, se importan las librerias de Keras y numpy.
Debido a que todos los datos son numéricos, se puede importar el archivo directo con numpy.
También se inicia el generador aleatorio con la variable seed, para que siempre obtengamos los mismos resultados.

In [23]:
from keras.models import Sequential
from keras.layers import Dense
import numpy

seed = 7
numpy.random.seed(seed)

# Cargar el dataset de los indios Pima.
dataset = numpy.loadtxt("DV.csv", delimiter=",")

# Dividir los datos en features y label.
X = dataset[:, :17]
Y = dataset[:, 17]
print('X \n',X,'\n Y\n',Y)

X 
 [[1.200e+01 2.017e+03 5.000e+00 ... 2.000e+00 2.000e+00 2.700e+04]
 [1.200e+01 2.013e+03 4.000e+00 ... 2.000e+00 2.000e+00 2.150e+04]
 [1.900e+01 2.019e+03 5.000e+00 ... 2.000e+00 2.000e+00 3.780e+04]
 ...
 [1.700e+01 1.992e+03 5.000e+00 ... 2.000e+00 2.000e+00 5.000e+03]
 [1.300e+01 2.012e+03 5.000e+00 ... 2.000e+00 2.000e+00 2.490e+04]
 [4.000e+00 2.020e+03 4.000e+00 ... 2.000e+00 1.000e+00 1.499e+04]] 
 Y
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

### Definir el modelo
Los modelos en Keras son definidos como una sequencias de capas. Podemos crear un modelo sequencia (Sequencial) y agregar capas una a una hasta que cumplan nuestros requerimientos.
El primer paso es asegurarnos que la primer capa tenga el numero correcto de entradas. Esto se consigue con el argumento input_dim, en este caso utilizaremos el valor de 8 debido a que son 8 variables que se alimentaran en la capa de entrada.
¿Cómo saber el numero de capas y sus tipos? Esta es una pregunta complicada pero normalmente se experimenta y a prueba y error se puede llegar a un resultado óptimo. En este caso vamos a utilizar una red conectada completamente con 3 capas.
Capas completamente conectadas son definidas mediante la clase Dense. En esta clase se define el numero de neuronas como primer argumento, como segundo argumento se define el método de inicialización, y la función de activación. En este caso vamos a iniciar los pesos de la red con un valor aleatorio muy pequeño utilizando una distribución uniforme (uniform), en Keras el valor va de 0 a 0.05. Otra opción seria utilizar una distribución de Gauss (normal).
En las primeras dos capas se definirá una función de activación relu y para la capa de salida una función sigmoid. En el pasado las funciones sigmoid y tanh eran las utilizadas en todas las capas, pero ha sido demostrado que el desempeño mejora utilizando la función rectifier como activación. En nuestro caso utilizamos la función sigmoid en la capada de salida para asegurarnos que el valor de salido oscila entre 0 y 1 y es mas fácil definir el resultado en la clasificación binaria.

In [24]:
model = Sequential()
model.add(Dense(12, input_dim=17, activation='relu'))
model.add(Dense(17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 12)                216       
                                                                 
 dense_4 (Dense)             (None, 17)                221       
                                                                 
 dense_5 (Dense)             (None, 1)                 18        
                                                                 
Total params: 455
Trainable params: 455
Non-trainable params: 0
_________________________________________________________________


### Compilar el modelo
Una vez que el modelo esta definido, se procede a compilarlo. Al compilar el modelo se mandan llamar las librerias en el backend, en nuestro caso Tensorflow. En este caso el backend automáticamente selecciona la mejor forma de representar la red neuronal para entrenamiento y realizar predicciones en el hardware. Cuando se compila el modelo, se deben definir algunas propiedades adicionales requeridas para el entrenamiento del modelo:
Especifica la función de perdida o loss function, que es utilizada para evaluar los pesos. También debes definir el optimizador utilizado para buscar entre los pesos de la red y algunas métricas opcionales que se require colectar y reportar durante el entrenamiento. En este ejemplo utilizaremos una función de perdida binary_crossentropy, que es una función logarítmica de perdida. Se utilizará una función para los calcular los gradientes llamada adam. Al ser un problema de clasificación binaria, se coleccionará y reportará la precision de la clasificación utilizando accuracy.

In [26]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

### Entrenar el modelo
Una vez que este definido y compilado el modelo, es tiempo de ejecutar el modelo con los datos. Se entrena el modelo llamando la función fit() en el modelo.
El proceso de entrenamiento se ejecuta cierto numero de veces utilizando el dataset, este numero de veces es llamado epochs, y se define utilizando el parámetro nb_epoch. También podemos definir el numero de instances que son evaluadas antes de que los pesos sean actualizados en la red neuronal. Este parámetro se llama batch_size. En este problema se definirá un numero pequeño de epochs (150) y un valor relativamente pequeño de el batch (10).

In [27]:
model.fit(X, Y, epochs=150, batch_size=10)


Epoch 1/150
94/94 [==============================] - 1s 1ms/step - loss: 298.1158 - accuracy: 0.8556
Epoch 2/150
94/94 [==============================] - 0s 925us/step - loss: 48.8775 - accuracy: 0.8481
Epoch 3/150
94/94 [==============================] - 0s 1ms/step - loss: 87.8017 - accuracy: 0.8695
Epoch 4/150
94/94 [==============================] - 0s 935us/step - loss: 144.8618 - accuracy: 0.8856
Epoch 5/150
94/94 [==============================] - 0s 871us/step - loss: 50.4376 - accuracy: 0.8342
Epoch 6/150
94/94 [==============================] - 0s 882us/step - loss: 20.4694 - accuracy: 0.8406
Epoch 7/150
94/94 [==============================] - 0s 882us/step - loss: 16.8855 - accuracy: 0.8556
Epoch 8/150
94/94 [==============================] - 0s 914us/step - loss: 14.2065 - accuracy: 0.8588
Epoch 9/150
94/94 [==============================] - 0s 946us/step - loss: 15.3045 - accuracy: 0.8642
Epoch 10/150
94/94 [==============================] - 0s 1ms/step - loss: 17.5939 - 

# Evalúar el modelo
Una ves entrenado el modelo utilizando el dataset completo, se debe evaluar el rendimiento de la red neuronal. Estos dara una idea de que tan bien modelamos nuestro dataset, pero no tendremos idea como se desempeñara el modelo con datos nuevos. En la realidad se debe de separar el dataset de training y el dataset de testing.
Se puede evaluar el modelo en tu dataset de training utilizando la función evaluation() del modelo, pasándole la misma entrada y salida utilizada para el entrenamiento. Esto generará una predicción por cada registro, se podrán colectar scores, average loss y otras métricas como accuracy.

In [28]:
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

30/30 [==============================] - 0s 897us/step - loss: 2.0602 - accuracy: 0.9198
accuracy: 91.98%
